### ISSUE TITLE
devel/gn 编译失败

### ISSUE THREAD

**Issue by AmberisMyShiba** [immortalwrt/packages#879] opened 2023-09-05 23:52 UTC
编译环境：manjaro gcc-13
以下是编译的出错信息。
`make[3]: Entering directory '/home/tef/openwrt/immortalwrt/feeds/packages/devel/gn'
MAKEFLAGS="" /home/tef/openwrt/immortalwrt/staging_dir/host/bin/ninja -v -j1 -C /home/tef/openwrt/immortalwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/out
ninja: Entering directory `/home/tef/openwrt/immortalwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/out'
[1/180] g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
FAILED: src/gn/desc_builder.o 
g++ -MMD -MF src/gn/desc_builder.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../src/gn/desc_builder.cc -o src/gn/desc_builder.o
../src/gn/desc_builder.cc: In member function 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)':
../src/gn/desc_builder.cc:179:21: error: redundant move in return statement [-Werror=redundant-move]
  179 |     return std::move(res);
      |            ~~~~~~~~~^~~~~
../src/gn/desc_builder.cc:179:21: note: remove 'std::move' call
../src/gn/desc_builder.cc: In instantiation of 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const std::vector<T>&) [with T = Value]':
../src/gn/desc_builder.cc:193:27:   required from here
../src/gn/desc_builder.cc:170:25: error: redundant move in return statement [-Werror=redundant-move]
  170 |     return std::move(res);
      |                         ^
../src/gn/desc_builder.cc:170:25: note: remove 'std::move' call
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/tef/openwrt/immortalwrt/build_dir/hostpkg/gn-2023-05-05-3dadaf0e/.built] Error 1
make[3]: Leaving directory '/home/tef/openwrt/immortalwrt/feeds/packages/devel/gn'
time: package/feeds/packages/gn/host-compile#3.80#0.23#4.64
    ERROR: package/feeds/packages/gn [host] failed to build.
make[2]: *** [package/Makefile:118: package/feeds/packages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/tef/openwrt/immortalwrt'
make[1]: *** [package/Makefile:114: /home/tef/openwrt/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/tef/openwrt/immortalwrt'
make: *** [/home/tef/openwrt/immortalwrt/include/toplevel.mk:232：world] 错误 2
`

**Comment by 1715173329** [comment] 2023-09-05 23:54
duplicate of #725

**Closed as completed** 2023-09-05 23:54 UTC
Labels: duplicate

**Comment by 1715173329** [comment] 2023-09-06 07:36
切回 clang build 了。

**Comment by AmberisMyShiba** [comment] 2023-09-06 08:39
> 切回 clang build 了。

真是把人纠结死了，gcc版本更新正好处在12和13的交接阶段，用clang还是gcc，还是以ubuntu最新的LTS的编译环境为主吧。
